query Home($locale: SiteLocale, $fallbackLocale: [SiteLocale!]) {
  home(locale: $locale, fallbackLocales: $fallbackLocale) {
    title
    pageBuilder {
      content {
        ...ContentFragment
      }
    }
  }
}
